config/routes.rb
Rails.application.routes.draw do
  # allow to personalize the routes for connection & registration
  # access at http://localhost:3000/users/#{replace by the value of the key sign in}
  devise_for :users, path_names: {
    sign_in: 'admin'
  }, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :contacts, only: %i[new create]
  get 'contacts/sent', to: 'contacts#sent', as: 'sent_contact'
  get '/qui_sommes_nous', to: 'pages#about', as: 'about'
  get '/soutenir', to: 'pages#support', as: 'support'
  get '/actualites', to: 'pages#news', as: 'news'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/repertoire_artisans', to: 'pages#directory_artisans', as: 'directory_artisans'
  get '/podcast', to: 'pages#podcast', as: 'podcast'
  get '/newsletter', to: 'pages#newsletter', as: 'newsletter'
  get '/visite', to: 'pages#visite', as: 'visite'

  # Partenariats
  get '/partenariat', to: 'pages#partnership', as: 'partnership'

  # Carnets des innovations w/ prospects
  get 'carnets_des_innovations', to: 'pages#notebooks', as: 'notebooks'

  resources :prospects, only: :create

  # Articles
  resources :articles, only: %i[index]
  get 'articles/civ', to: 'articles#civ', as: 'articleciv'

  # Posts with SAAS
  # resources :posts, only: %i[index new create show destroy edit update]
  get 'blog', to: 'posts#index', as: 'posts'
  get 'blog/nouvel-article', to: 'posts#new', as: 'new_post'
  post 'blog', to: 'posts#create'
  get 'blog/:id', to: 'posts#show', as: 'post'
  get 'blog/:id/modifier-article', to: 'posts#edit', as: 'edit_post'
  patch 'blog/:id', to: 'posts#update'
  delete 'blog/:id', to: 'posts#destroy'

  # Legal
  get '/mentionslegales', to: 'pages#legal', as: 'legal'
end

app/views/shared/_flash_message.html.erb
<% flash.each do |flash_type, message| %>
  <div class="text-green bg-beige py-[10px] px-[20px] border-solid border-green border-2 rounded-sm lg:text-sm text-3xl animate-fade"
        data-controller='flash-removal'
        data-action='animationend->flash-removal#remove'
        >
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="lg:px-40 px-8 mx-auto my-3">
  <div class="grid grid-cols-1 items-center lg:grid-cols-4">
    <div class="grid justify-items-start">

      <% unless params[:action] == 'newsletter' %>
        <p class=" font-bold mb-1">Inscrivez-vous à notre newsletter !</p>
        <%= link_to "S'abonner", newsletter_path, class:"block rounded-sm bg-orange hover:bg-green hover:text-beige text-beige font-bold text-3xl lg:text-base font-sans text-center py-2 px-4" %>
      <% end %>

    </div>

    <div class="flex flex-row lg:mt-4 space-x-6 justify-end lg:justify-center mt-0 text-5xl lg:text-3xl">
      <a href="https://facebook.com/histoiresdartisans" class="text-green hover:text-orange" target="_blank">
        <i class="fab fa-facebook"></i>
      </a>
      <a href="https://instagram.com/histoiresdartisans/" class="text-green hover:text-orange" target="_blank">
          <i class="fab fa-instagram"></i>
      </a>
      <a href="https://twitter.com/histoireartisan" class="text-green hover:text-orange" target="_blank">
          <i class="fab fa-twitter"></i>
      </a>
      <a
        href="https://fr.linkedin.com/company/histoiresdartisans?trk=organization_guest_main-feed-card_feed-reaction-header"
        class="text-green hover:text-orange"
        target="_blank">
          <i class="fab fa-linkedin"></i>
      </a>
    </div>

    <div class="grid justify-items-start lg:justify-items-end">
        <a
          href="<%= legal_path %>"
          class="text-2xl lg:text-base text-green font-monospace hover:underline"
          target="_blank">
          Mentions Légales
        </a>
    </div>

    <div class="grid justify-items-start lg:justify-items-end">
      <span class="text-2xl lg:text-base text-green font-monospace">© 2023
        <a
          href="https://www.linkedin.com/in/lisa-millet"
          class="text-2xl lg:text-base text-green font-monospace hover:underline"
          target="_blank">
          Histoires d'Artisans
        </a>
      </span>
    </div>


</div>

app/views/shared/_navbar.html.erb
<div class="w-full bg-beige">

  <div class="flex flex-wrap items-center justify-between lg:px-40 px-8 my-2">
    <%= link_to root_path, class: "flex items-center" do %>
      <img
        src="https://res.cloudinary.com/dvuyabyaw/image/upload/v1679515699/HdA/Transparents/Orange_Transparent/Orange_1_-small_lf1gm9.png"
        class="h-32 lg:h-14 mx-auto"
        alt="Histoires d'Artisans Logo" />
    <% end %>

    <button
      data-collapse-toggle="navbar-dropdown"
      type="button"
      class="inline-flex items-center ml-3 text-sm text-green rounded-lg lg:hidden hover:orange focus:outline-none"
      aria-controls="navbar-dropdown"
      aria-expanded="false">
      <span class="sr-only">Menu</span>
      <svg
        class="w-20 h-20"
        aria-hidden="true"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg">
        <path
          fill-rule="evenodd"
          d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
          clip-rule="evenodd">
        </path>
      </svg>
    </button>

    <div class="hidden w-full lg:block lg:w-auto" id="navbar-dropdown">
      <ul class="font-monospace flex flex-col lg:p-0 mt-4 lg:flex-row lg:space-x-8 lg:mt-0">
        <li>
          <button id="dropdownNavbarLink"
            data-dropdown-toggle="targetEl1"
            class="text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2">
            Notre association
            <svg
              class="w-5 h-5 ml-1"
              aria-hidden="true"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path
                fill-rule="evenodd"
                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                clip-rule="evenodd">
                </path>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="targetEl1" class="z-50 hidden font-monospace bg-beige divide-y divide-green shadow">
                <ul class="py-2 px-4 text-sm text-green" aria-labelledby="dropdownLargeButton">
                  <li>
                    <%= link_to 'Qui sommes-nous', about_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to 'Nous soutenir', support_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to "Nos partenaires", partnership_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                </ul>
            </div>
        </li>
        <li>
          <button id="dropdownNavbarLink"
            data-dropdown-toggle="targetEl2"
            class="text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2">
            Nos actions
            <svg
              class="w-5 h-5 ml-1"
              aria-hidden="true"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path
                fill-rule="evenodd"
                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                clip-rule="evenodd">
                </path>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="targetEl2" class="z-50 hidden font-monospace bg-beige divide-y divide-green shadow">
                <ul class="py-2 px-4 text-sm text-green" aria-labelledby="dropdownLargeButton">
                  <li>
                    <%= link_to 'Notre journal', posts_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to "Nos Masterclasses d'artisans", visite_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to "Nos carnets des innovations", notebooks_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to 'Notre podcast', podcast_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>
                  <li>
                    <%= link_to "Notre répertoire d'artisans", directory_artisans_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                  </li>

                </ul>
            </div>
        </li>
        <li>
          <%= link_to "Nous contacter", new_contact_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
        </li>
        <% if user_signed_in? %>
          <li>
            <button id="dropdownNavbarLink"
              data-dropdown-toggle="targetEl3"
              class="text-4xl lg:text-base font-bold font-monospace text-orange items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2">
              <%= current_user.email %>
              <svg
                class="w-5 h-5 ml-1"
                aria-hidden="true"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path
                  fill-rule="evenodd"
                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                  clip-rule="evenodd">
                  </path>
                </svg>
              </button>
              <!-- Dropdown menu -->
              <div id="targetEl3" class="z-50 hidden font-monospace bg-beige divide-y divide-green shadow">
                  <ul class="py-2 px-4 text-sm text-green" aria-labelledby="dropdownLargeButton">
                    <li>
                      <%= link_to 'Profil', podcast_path, class:"text-4xl lg:text-base font-bold font-monospace text-green items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                    </li>
                    <li>
                      <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class:"text-4xl lg:text-base font-bold font-monospace text-orange items-center flex justify-end w-full hover:bg-beige hover:text-orange px-4 py-2"%>
                    </li>
                  </ul>
              </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>